[tool.poetry]
name = "ls"
version = "0.1.0"
description = ""
authors = ["-- <yaliyarov@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
